src.dir=src/main
web.dir=${src.dir}/webapp
build.dir=build
lib.dir=lib
dist.dir=dist
resources.dir=${src.dir}/resources
sounds.dir=sounds
tmp.dir=tmp

test.src.dir=src/test
test.build.dir=${build.dir}/test

test.reports.dir=${test.build.dir}/reports

# SVN report settings
svn.report.dir=reports
svn.commit.message=Automated commit: add JUnit test report

app.name=web3
app.version=1.0.0
