<project name="web-lab3" basedir=".">


    <property file="build.properties" />

    <path id="classpath">
        <fileset dir="${lib.dir}" includes="**/*.jar" />
    </path>

    <target name="clean">
        <delete dir="${build.dir}" failonerror="true" />
        <delete dir="${dist.dir}" failonerror="true" />
        <delete dir="${tmp.dir}" failonerror="true" />
    </target>

    <target name="compile" depends="clean">
        <mkdir dir="${build.dir}" />
        <javac srcdir="${src.dir}"
            destdir="${build.dir}"
            includeantruntime="false"
            classpathref="classpath">

            <compilerarg value="-processorpath" />
            <compilerarg path="${lib.dir}/lombok-1.18.30.jar" />

        </javac>

        <copy todir="${build.dir}">
            <fileset dir="${resources.dir}" />
        </copy>
    </target>

    <target name="build" depends="compile">
        <mkdir dir="${dist.dir}" />
        <war destfile="${dist.dir}/${app.name}-${app.version}.war"
            webxml="${web.dir}/WEB-INF/web.xml">
            <manifest>
                <attribute name="Implementation-Version" value="${app.version}" />
            </manifest>
            <fileset dir="${web.dir}" />
            <classes dir="${build.dir}" />
            <lib dir="${lib.dir}" />
        </war>
    </target>

    <target name="scp" depends="build">
        <input message="Select target server:"
            addproperty="selected.server"
            validargs="helios" />

        <antcall target="scp-${selected.server}" />
    </target>


    <target name="scp-helios">
        <scp file="${dist.dir}/${app.name}-${app.version}.war"
            todir="${helios.user}:${helios.password}@${helios.host}:${helios.destdir}"
            port="${helios.port}"
            trust="true"
            verbose="true" />
    </target>

    <target name="music" depends="build">
        <sound>
            <success source="${sounds.dir}/sound.wav" />
            <fail source="${sounds.dir}/sound.wav" />
        </sound>
    </target>

    <target name="xml">
        <xmlvalidate lenient="true" failonerror="true">
            <fileset dir="${src.dir}" includes="**/*.xml,**/*.xhtml" />
        </xmlvalidate>
    </target>

    <macrodef name="build-revision">
        <attribute name="rev" />
        <sequential>
            <exec executable="git" failonerror="true">
                <arg line="clone --local --no-hardlinks . ${tmp.dir}/rev@{rev}" />
            </exec>
            <exec executable="git" failonerror="true" dir="${tmp.dir}/rev@{rev}">
                <arg line="-c advice.detachedHead=false checkout HEAD~@{rev}" />
            </exec>
            <ant antfile="build.xml"
                dir="${tmp.dir}/rev@{rev}"
                target="build"
                inheritAll="false" />
        </sequential>
    </macrodef>

    <target name="team" depends="clean">
        <delete dir="${tmp.dir}" failonerror="false" />
        <mkdir dir="${tmp.dir}" />

        <build-revision rev="1" />
        <build-revision rev="2" />
        <build-revision rev="3" />

        <zip destfile="${dist.dir}/team.zip">
            <fileset dir="${tmp.dir}" includes="**/dist/*.war" />
        </zip>

    </target>

    <target name="git-hashes">
        <exec executable="git"
              outputproperty="git.ls.raw"
              failonerror="true">
            <arg line="ls-files -s" />
        </exec>
        <echo file="${build.dir}/.git-ls-tmp" message="${git.ls.raw}" />
        <checksum file="${build.dir}/.git-ls-tmp"
                  algorithm="MD5"  property="project.files.md5" />
        <checksum file="${build.dir}/.git-ls-tmp"
                  algorithm="SHA-1" property="project.files.sha1" />
        <delete file="${build.dir}/.git-ls-tmp" />
    </target>

    <target name="delombok">
        <mkdir dir="${build.dir}/delombok" />
        <java jar="${lib.dir}/lombok-1.18.30.jar"
              fork="true"
              failonerror="true">
            <arg value="delombok" />
            <arg value="-d" />
            <arg file="${build.dir}/delombok" />
            <arg value="--classpath" />
            <arg pathref="classpath" />
            <arg file="${src.dir}" />
        </java>
    </target>

    <target name="javadoc" depends="delombok">
        <mkdir dir="${build.dir}/javadoc" />
        <javadoc destdir="${build.dir}/javadoc"
                 classpathref="classpath"
                 encoding="UTF-8" docencoding="UTF-8" charset="UTF-8">
            <fileset dir="${build.dir}/delombok" includes="**/*.java" />
        </javadoc>
    </target>

    <target name="doc" depends="build, git-hashes, javadoc">
        <jar destfile="${dist.dir}/${app.name}-${app.version}.war"
             update="true">
            <manifest>
                <attribute name="Project-Files-MD5"  value="${project.files.md5}" />
                <attribute name="Project-Files-SHA1" value="${project.files.sha1}" />
            </manifest>
            <zipfileset dir="${build.dir}/javadoc" prefix="javadoc" />
        </jar>
    </target>


</project>